### ISSUE TITLE
how to use on nuxt.js

### ISSUE THREAD

**Issue by greetfish** [cookforweb/vue-admanager#2]
Hello dear,
do you have any idea to use your plugin on nuxt.js ?

**Comment by greetfish** [comment]
ignore me ,I use the tags generated by ad manager, no plugin ,and it get work 。
here was my useage

## import js in head
`
script: [
      { src: 'https://securepubads.g.doubleclick.net/tag/js/gpt.js', async: true }
    ]
`

## mounted on client side
`
mounted () {
    window.addEventListener('scroll', this.handleArticleScoll, true)
    this.$nextTick(() => {
      if (process.client) {
        window.googletag = window.googletag || { cmd: [] }
        console.log(window.googletag)
        window.googletag.cmd.push(function () {
          window.googletag.defineSlot('/21988******/article/center_top', [[320, 50], [970, 90], [970, 250], [728, 90], [320, 100]], 'div-gpt-ad-162757********').addService(window.googletag.pubads())
          window.googletag.pubads().enableSingleRequest()
          window.googletag.enableServices()
        })
        window.googletag.cmd.push(function () { window.googletag.display('div-gpt-ad-1627579555960-0') })
      }
    })
  }
`

## make div on html
`
"<div id='div-gpt-ad-1627***********' style='min-width: 320px; min-height: 50px;'></div>"
`

**Comment by andredezzy** [comment]
Thank you @greetfish :D
It worked for me, I was one ago day trying to show ads on my page.
